version: '3'

volumes:
  postgres-data:
    name: postgres-data
    driver: local
  redis_data:
    name: redis-data
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 3001
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # networks: нащо це?
      # - my-network

